// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SaveCustomerTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void saveCustomer() {
    driver.get("http://localhost:3000/add-customer");
    driver.manage().window().setSize(new Dimension(1536, 736));
    driver.findElement(By.id("formBasicUserName")).click();
    driver.findElement(By.id("formBasicUserName")).sendKeys("991053096V");
    driver.findElement(By.id("formBasicFirstName")).sendKeys("Supun");
    driver.findElement(By.id("formBasicLastName")).sendKeys("Sankalpa");
    driver.findElement(By.id("formBasicNumber")).sendKeys("0710588165");
    driver.findElement(By.cssSelector(".col-lg-6:nth-child(1) #formBasicNumber")).click();
    driver.findElement(By.cssSelector(".col-lg-6:nth-child(1) #formBasicNumber")).sendKeys("Dope");
    driver.findElement(By.cssSelector(".row:nth-child(3) > .col-lg-6:nth-child(2) #formBasicNumber")).click();
    driver.findElement(By.cssSelector(".row:nth-child(3) > .col-lg-6:nth-child(2) #formBasicNumber")).sendKeys("Bentota");
    driver.findElement(By.cssSelector(".col-lg-6:nth-child(3) #formBasicNumber")).click();
    driver.findElement(By.cssSelector(".col-lg-6:nth-child(3) #formBasicNumber")).sendKeys("262/B");
    driver.findElement(By.id("formBasicPassword")).click();
    driver.findElement(By.id("formBasicPassword")).sendKeys("nsrm5566");
    driver.findElement(By.id("formBasicConfPassword")).click();
    driver.findElement(By.id("formBasicConfPassword")).sendKeys("nsrm5566");
    driver.findElement(By.cssSelector(".btn-success")).click();
  }
}
